//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// SutInstaller.rc で使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_SUTINSTALLER_DIALOG         102
#define IDS_ADDIN_NAME                  129
#define IDS_EXCEL_LIST_COLUMN_VERSION   130
#define IDS_EXCEL_LIST_COLUMN_PATH      131
#define IDI_ICON1                       131
#define IDR_MAINFRAME                   131
#define IDS_INFO_EXCEL_LAUNCHED_FAILED  132
#define IDS_INFO_EXCEL_ADDED_ADDIN_SUCCESS 133
#define IDS_INFO_EXCEL_ADDED_ADDIN_FAILED 134
#define IDS_INFO_EXCEL_REMOVE_ADDIN_SUCCESS 135
#define IDS_INFO_EXCEL_REMOVE_ADDIN_FAILED 136
#define IDB_SUT_ICON2                   136
#define IDS_INFO_EXCEL_REACTION_PROCESS 137
#define IDB_BITMAP1                     137
#define IDB_SUT_ICON                    137
#define IDS_INFO_EXCEL_REMOVE_ADDIN_NOT_FOUND 138
#define IDS_ADDIN_FILE_NAME             139
#define IDS_INFO_ADDIN_FILE_NOT_FOUND   140
#define IDS_INFO_EXCEL_PROCESS_EXIST    141
#define IDS_INFO_CHECK_ADDIN_INSTALL_UNEXPECTED 142
#define IDS_INFO_CHECK_ADDIN_INSTALL_NG 143
#define IDS_INFO_CHECK_ADDIN_INSTALL_NG_DETAIL 144
#define IDS_INFO_COMPLETELY_DELETE_ADDIN_CONFIRM 145
#define IDS_INFO_COMPLETELY_DELETE_ADDIN_CONFIRM2 146
#define IDS_INFO_COMPLETELY_DELETE_ADDIN_OK 147
#define IDS_INFO_COMPLETELY_DELETE_ADDIN_NOT_FOUND 148
#define IDS_INFO_COMPLETELY_DELETE_ADDIN_SUSPEND 149
#define IDS_INFO_COMPLETELY_DELETE_ADDIN_UNEXPECTED 150
#define IDS_INFO_COMPLETELY_DELETE_ADDIN_EXCEL_EXIT_PROCESS_RETRY 151
#define IDS_INFO_COMPLETELY_DELETE_ADDIN_EXCEL_EXIT_PROCESS_ERROR 152
#define IDS_INFO_EXCEL_ADDED_ADDIN_ALREADY_INSTALLED 153
#define IDS_COM_FILE_SUT_RED            154
#define IDS_INFO_COM_INSTALLED_FAILED   155
#define IDS_INFO_COM_UNINSTALLED_FAILED 156
#define IDS_COM_CUR_DIR                 157
#define IDS_SELECTED_ONE_MORE           158
#define IDS_SELECTED_ONE_MORE_OR_UNINSTALL_OPTION 159
#define IDS_INFO_REG_DELETE_FAILED      160
#define IDS_INFO_COM_UNINSTALLED_SUCCESS 161
#define IDS_INFO_REG_DELETE_SUCCESS     162
#define IDS_INFO_SECURITY_BLOCK_RELEASE_FAILED 163
#define IDC_ICON2                       1000
#define IDC_SUT_ICON2                   1000
#define IDC_INSTALLED_EXCEL_LIST        1001
#define IDC_INSTALL                     1002
#define IDC_UNINSTALL                   1003
#define IDC_SUT_ICON                    1004
#define IDC_CHK_REG_DELETE              1007
#define IDC_STATIC_TITLE                1009
#define IDC_STATIC_TITLE2               1010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
