SELECT
    TRIM(S.SCHEMA_NAME)      AS CONSTRAINT_SCHEMA
   ,TRIM(TC.CONSTRAINT_NAME) AS CONSTRAINT_NAME
   ,CASE TRIM(TC.CONSTRAINT_NAME)
    WHEN TRIM('') THEN CAST(TC.DB_CODE         AS VARCHAR(30)) || '_' ||
                       CAST(TC.SCHEMA_CODE     AS VARCHAR(30)) || '_' ||
                       CAST(TC.TABLE_CODE      AS VARCHAR(30)) || '_' ||
                       CAST(TC.CONSTRAINT_CODE AS VARCHAR(30)) || '_' || TRIM(TC.CONSTRAINT_TYPE)
    ELSE TRIM(TC.CONSTRAINT_NAME)
    END                  AS CONSTRAINT_NAME
   ,TRIM(S.SCHEMA_NAME)  AS TABLE_SCHEMA
   ,TRIM(T.TABLE_NAME)   AS TABLE_NAME
   ,TRIM(C.COLUMN_NAME)  AS COLUMN_NAME
   ,TRIM(' ')            AS REF_TABLE_SCHEMA
   ,TRIM(' ')            AS REF_TABLE_NAME
   ,TRIM(' ' )           AS REF_COLUMN_NAME
   ,CASE TRIM(TC.CONSTRAINT_TYPE)
    WHEN TRIM('PK') THEN TRIM('P')
    WHEN TRIM('UK') THEN TRIM('U')
    ELSE TRIM(TC.CONSTRAINT_TYPE)
    END                  AS CONSTRAINT_TYPE
FROM
      RDBII_SYSTEM.RDBII_CONSTRAINT   TC
     ,RDBII_SYSTEM.RDBII_COLUMN_USAGE KU
     ,RDBII_SYSTEM.RDBII_SCHEMA  S
     ,RDBII_SYSTEM.RDBII_TABLE   T
     ,RDBII_SYSTEM.RDBII_COLUMN  C
WHERE
    TC.DB_CODE = KU.DB_CODE
AND TC.SCHEMA_CODE = KU.OBJ_SCHEMA_CODE
AND TC.CONSTRAINT_CODE = KU.OBJECT_CODE
AND TC.DB_CODE = S.DB_CODE
AND TC.SCHEMA_CODE = S.SCHEMA_CODE
AND TC.DB_CODE = T.DB_CODE
AND TC.SCHEMA_CODE = T.SCHEMA_CODE
AND TC.TABLE_CODE  = T.TABLE_CODE
AND KU.DB_CODE = C.DB_CODE
AND KU.SCHEMA_CODE = C.SCHEMA_CODE
AND KU.TABLE_CODE  = C.TABLE_CODE
AND KU.COLUMN_CODE = C.COLUMN_CODE
AND S.DB_NAME = ${db_name}
AND ${condition}
ORDER BY
    CAST(TC.DB_CODE AS VARCHAR(30)) || '_' || CAST(TC.SCHEMA_CODE  AS VARCHAR(30)) || '_' || CAST(TC.TABLE_CODE AS VARCHAR(30)) || '_' || CAST(TC.CONSTRAINT_CODE AS VARCHAR(30)) || '_' ||   TRIM(TC.CONSTRAINT_TYPE)
   ,KU.ORDINAL_POSITION